### ISSUE TITLE
Index out of bounds Exception

### ISSUE THREAD

**Issue by vcucek** [CloudScale-Project/Extractor#1]
During a project extraction, I get the following exception:

org.eclipse.gmt.modisco.java.emf.impl.IfStatementImpl@56eebafb
org.eclipse.core.runtime.CoreException: Please, check your discoverer and SoMoX configuration. at 
eu.cloudscaleproject.env.extractor.util.ExtractorRunJob.runSomox(ExtractorRunJob.java:182) at 
eu.cloudscaleproject.env.extractor.util.ExtractorRunJob.run(ExtractorRunJob.java:71) at 
eu.cloudscaleproject.env.extractor.alternatives.ConfingAlternative.doRun(ConfingAlternative.java:119) at 
eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative$1.run(AbstractConfigAlternative.java:96) at 
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313) at 
org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295) at 
eu.cloudscaleproject.env.toolchain.resources.types.AbstractConfigAlternative.run(AbstractConfigAlternative.java:91) at 
eu.cloudscaleproject.env.toolchain.ui.ConfigEditorView$AlternativeRunJob.run(ConfigEditorView.java:270) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

Caused by: 
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: 
index=6, size=6
     at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346) at 
org.somox.gast2seff.visitors.SwitchStatementHelper.createBlockListFromSwitchStatement(SwitchStatementHelper.java:45) at 
org.somox.gast2seff.visitors.FunctionCallClassificationVisitor.caseSwitchStatement(FunctionCallClassificationVisitor.java:130) at 
org.somox.gast2seff.visitors.FunctionCallClassificationVisitor.caseSwitchStatement(FunctionCallClassificationVisitor.java:1) at 
org.eclipse.gmt.modisco.java.emf.util.JavaSwitch.doSwitch(JavaSwitch.java:1015) at 
org.eclipse.gmt.modisco.java.emf.util.JavaSwitch.doSwitch(JavaSwitch.java:207) at 
org.eclipse.gmt.modisco.java.emf.util.JavaSwitch.doSwitch(JavaSwitch.java:195) at 
org.somox.gast2seff.jobs.GAST2SEFFJob.createSeff(GAST2SEFFJob.java:331) at 
org.somox.gast2seff.jobs.GAST2SEFFJob.generateSEFFForGASTBehaviour(GAST2SEFFJob.java:418)
     at org.somox.gast2seff.jobs.GAST2SEFFJob.execute(GAST2SEFFJob.java:187) at 
eu.cloudscaleproject.env.extractor.util.ExtractorRunJob.runSomox(ExtractorRunJob.java:164)
     ... 8 more

**Comment by snowball77** [comment]
Hi,
can you share the code, the configuration, the MoDisCo model, or any further details to reproduce the issue?
